// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto

/*
Package cluster is a generated protocol buffer package.

It is generated from these files:
	github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto

It has these top-level messages:
	ContainersRequest
	ImagesRequest
	NodesRequest
	ContainersResponse
	ImagesResponse
	Node
	NodesResponse
	Container
	HealthRequest
	NodeHealth
	HealthResponse
*/
package cluster

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// skipping weak import google_api1 "github.com/gogo/googleapis"
import _ "github.com/gogo/protobuf/gogoproto"
import stellar_services_node_v1 "github.com/ehazlett/stellar/api/services/node/v1"
import stellar_services_health_v1 "github.com/ehazlett/stellar/api/services/health/v1"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ContainersRequest struct {
	Filters []string `protobuf:"bytes,1,rep,name=filters" json:"filters,omitempty"`
}

func (m *ContainersRequest) Reset()                    { *m = ContainersRequest{} }
func (m *ContainersRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainersRequest) ProtoMessage()               {}
func (*ContainersRequest) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{0} }

func (m *ContainersRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ImagesRequest struct {
}

func (m *ImagesRequest) Reset()                    { *m = ImagesRequest{} }
func (m *ImagesRequest) String() string            { return proto.CompactTextString(m) }
func (*ImagesRequest) ProtoMessage()               {}
func (*ImagesRequest) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{1} }

type NodesRequest struct {
}

func (m *NodesRequest) Reset()                    { *m = NodesRequest{} }
func (m *NodesRequest) String() string            { return proto.CompactTextString(m) }
func (*NodesRequest) ProtoMessage()               {}
func (*NodesRequest) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{2} }

type ContainersResponse struct {
	Containers []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
}

func (m *ContainersResponse) Reset()                    { *m = ContainersResponse{} }
func (m *ContainersResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainersResponse) ProtoMessage()               {}
func (*ContainersResponse) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{3} }

func (m *ContainersResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ImagesResponse struct {
	Images []*stellar_services_node_v1.Image `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
}

func (m *ImagesResponse) Reset()                    { *m = ImagesResponse{} }
func (m *ImagesResponse) String() string            { return proto.CompactTextString(m) }
func (*ImagesResponse) ProtoMessage()               {}
func (*ImagesResponse) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{4} }

func (m *ImagesResponse) GetImages() []*stellar_services_node_v1.Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Node struct {
	ID      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{5} }

func (m *Node) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type NodesResponse struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *NodesResponse) Reset()                    { *m = NodesResponse{} }
func (m *NodesResponse) String() string            { return proto.CompactTextString(m) }
func (*NodesResponse) ProtoMessage()               {}
func (*NodesResponse) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{6} }

func (m *NodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Container struct {
	Container *stellar_services_node_v1.Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Node      *Node                               `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{7} }

func (m *Container) GetContainer() *stellar_services_node_v1.Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *Container) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{8} }

type NodeHealth struct {
	Node   *Node                                  `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Health *stellar_services_health_v1.NodeHealth `protobuf:"bytes,2,opt,name=health" json:"health,omitempty"`
}

func (m *NodeHealth) Reset()                    { *m = NodeHealth{} }
func (m *NodeHealth) String() string            { return proto.CompactTextString(m) }
func (*NodeHealth) ProtoMessage()               {}
func (*NodeHealth) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{9} }

func (m *NodeHealth) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeHealth) GetHealth() *stellar_services_health_v1.NodeHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

type HealthResponse struct {
	Nodes []*NodeHealth `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptorCluster, []int{10} }

func (m *HealthResponse) GetNodes() []*NodeHealth {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*ContainersRequest)(nil), "stellar.services.cluster.v1.ContainersRequest")
	proto.RegisterType((*ImagesRequest)(nil), "stellar.services.cluster.v1.ImagesRequest")
	proto.RegisterType((*NodesRequest)(nil), "stellar.services.cluster.v1.NodesRequest")
	proto.RegisterType((*ContainersResponse)(nil), "stellar.services.cluster.v1.ContainersResponse")
	proto.RegisterType((*ImagesResponse)(nil), "stellar.services.cluster.v1.ImagesResponse")
	proto.RegisterType((*Node)(nil), "stellar.services.cluster.v1.Node")
	proto.RegisterType((*NodesResponse)(nil), "stellar.services.cluster.v1.NodesResponse")
	proto.RegisterType((*Container)(nil), "stellar.services.cluster.v1.Container")
	proto.RegisterType((*HealthRequest)(nil), "stellar.services.cluster.v1.HealthRequest")
	proto.RegisterType((*NodeHealth)(nil), "stellar.services.cluster.v1.NodeHealth")
	proto.RegisterType((*HealthResponse)(nil), "stellar.services.cluster.v1.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cluster service

type ClusterClient interface {
	Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error)
	Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := grpc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Containers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error) {
	out := new(ImagesResponse)
	err := grpc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Images", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error) {
	out := new(NodesResponse)
	err := grpc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Nodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	Containers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	Images(context.Context, *ImagesRequest) (*ImagesResponse, error)
	Nodes(context.Context, *NodesRequest) (*NodesResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Containers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Containers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Containers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Containers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Images_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Images(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Images",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Images(ctx, req.(*ImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Nodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Nodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Nodes(ctx, req.(*NodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellar.services.cluster.v1.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Containers",
			Handler:    _Cluster_Containers_Handler,
		},
		{
			MethodName: "Images",
			Handler:    _Cluster_Images_Handler,
		},
		{
			MethodName: "Nodes",
			Handler:    _Cluster_Nodes_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Cluster_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto",
}

func init() {
	proto.RegisterFile("github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto", fileDescriptorCluster)
}

var fileDescriptorCluster = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xd9, 0x96, 0xa9, 0x77, 0x6c, 0x68, 0x06, 0xa1, 0x52, 0x90, 0x3a, 0x32, 0x09, 0xc6,
	0x10, 0x89, 0x5a, 0x84, 0x40, 0x9a, 0x86, 0xb4, 0x0d, 0xa1, 0xf5, 0x05, 0xa4, 0x3c, 0x21, 0xc4,
	0x8b, 0xd7, 0x98, 0xd4, 0x52, 0x1a, 0x97, 0xd8, 0xad, 0x04, 0x8f, 0x20, 0xbe, 0x80, 0xaf, 0xe1,
	0x3b, 0x78, 0xe7, 0x01, 0xf1, 0x21, 0xc8, 0xf6, 0x75, 0xda, 0x08, 0x68, 0x03, 0x4f, 0x75, 0xec,
	0x73, 0xce, 0x3d, 0xf7, 0xfa, 0xd4, 0x70, 0x92, 0x71, 0x35, 0x9a, 0x5e, 0x44, 0x43, 0x31, 0x8e,
	0xd9, 0x88, 0x7e, 0xc8, 0x99, 0x52, 0xb1, 0x54, 0x2c, 0xcf, 0x69, 0x19, 0xd3, 0x09, 0x8f, 0x25,
	0x2b, 0x67, 0x7c, 0xc8, 0x64, 0x3c, 0xcc, 0xa7, 0x52, 0xb1, 0x32, 0x9e, 0xf5, 0xdc, 0x32, 0x9a,
	0x94, 0x42, 0x09, 0x72, 0x13, 0xe1, 0x91, 0x83, 0x46, 0xee, 0x7c, 0xd6, 0xeb, 0xdc, 0xca, 0x84,
	0xc8, 0x72, 0x66, 0xa4, 0x68, 0x51, 0x08, 0x45, 0x15, 0x17, 0x85, 0xb4, 0xd4, 0xce, 0xb5, 0x4c,
	0x64, 0xc2, 0x2c, 0x63, 0xbd, 0xc2, 0xdd, 0x6e, 0xad, 0x6e, 0x21, 0x52, 0xa6, 0x8b, 0xea, 0x5f,
	0x04, 0xec, 0xd7, 0x00, 0x23, 0x46, 0x73, 0x35, 0xd2, 0x10, 0xbb, 0xb2, 0xa0, 0xf0, 0x01, 0xec,
	0x9e, 0x89, 0x42, 0x51, 0x5e, 0xb0, 0x52, 0x26, 0xec, 0xdd, 0x94, 0x49, 0x45, 0xda, 0xb0, 0xf9,
	0x96, 0xe7, 0x8a, 0x95, 0xb2, 0xed, 0xed, 0xad, 0x1d, 0xb4, 0x12, 0xf7, 0x19, 0x5e, 0x81, 0xed,
	0xc1, 0x98, 0x66, 0xcc, 0x41, 0xc3, 0x1d, 0xb8, 0xfc, 0x42, 0xa4, 0xf3, 0xef, 0x37, 0x40, 0x16,
	0xf5, 0xe4, 0x44, 0x14, 0x92, 0x91, 0xe7, 0x00, 0xc3, 0x6a, 0xd7, 0x68, 0x6e, 0xf5, 0xef, 0x44,
	0x4b, 0x26, 0x12, 0x55, 0x22, 0xc9, 0x02, 0x33, 0x1c, 0xc0, 0x8e, 0x2b, 0x8f, 0xca, 0x8f, 0x21,
	0xe0, 0x66, 0x07, 0x55, 0xbb, 0xbf, 0xab, 0x9a, 0x91, 0xcc, 0x7a, 0x91, 0x61, 0x26, 0x08, 0x0f,
	0x9f, 0xc0, 0xba, 0x36, 0x4e, 0xae, 0x83, 0xcf, 0xd3, 0xb6, 0xb7, 0xe7, 0x1d, 0xb4, 0x4e, 0x83,
	0x1f, 0xdf, 0xbb, 0xfe, 0xe0, 0x59, 0xe2, 0xf3, 0x54, 0xcf, 0x80, 0xa6, 0x69, 0xc9, 0xa4, 0x6c,
	0xfb, 0xfa, 0x30, 0x71, 0x9f, 0xe1, 0x39, 0x6c, 0x63, 0xcb, 0x95, 0x87, 0x0d, 0x5d, 0xc3, 0x59,
	0xb8, 0xbd, 0xb4, 0x31, 0x4d, 0x4d, 0x2c, 0x3e, 0xfc, 0xec, 0x41, 0xab, 0x6a, 0x94, 0x9c, 0x40,
	0xab, 0x6a, 0xd5, 0x18, 0xda, 0xea, 0xef, 0xff, 0xbd, 0x9b, 0xf9, 0x80, 0xe6, 0x2c, 0xf2, 0x08,
	0xd6, 0xf5, 0xb9, 0x71, 0xdc, 0xc8, 0x88, 0x81, 0xeb, 0x5b, 0x3d, 0x37, 0xa1, 0x70, 0xb7, 0xf8,
	0xc9, 0x03, 0xd0, 0xe7, 0x76, 0xb7, 0x92, 0xf5, 0xfe, 0x49, 0x96, 0x3c, 0x85, 0xc0, 0x66, 0x0d,
	0xfd, 0xfc, 0xe1, 0xc6, 0x31, 0x8b, 0xc8, 0x43, 0x13, 0xc8, 0x0a, 0x5f, 0xc2, 0x8e, 0xb3, 0x85,
	0x93, 0x3e, 0xae, 0x4f, 0xfa, 0xee, 0x4a, 0x27, 0xc8, 0xb7, 0xac, 0xfe, 0xd7, 0x35, 0xd8, 0x3c,
	0xb3, 0x00, 0x32, 0x06, 0x98, 0x07, 0x95, 0x44, 0xcd, 0xc2, 0xe8, 0x62, 0xde, 0x89, 0x1b, 0xe3,
	0xd1, 0x39, 0x85, 0xc0, 0x26, 0x97, 0x1c, 0x2e, 0xa5, 0xd6, 0xfe, 0x5d, 0x9d, 0xfb, 0x8d, 0xb0,
	0x58, 0xe2, 0x3d, 0x6c, 0x98, 0x5c, 0x92, 0x7b, 0x2b, 0xc7, 0x52, 0x15, 0x38, 0x6c, 0x02, 0xb5,
	0xfa, 0xe1, 0x8d, 0x8f, 0xdf, 0x7e, 0x7e, 0xf1, 0xaf, 0x92, 0xdd, 0x85, 0xc7, 0xcd, 0xbc, 0x37,
	0x52, 0x77, 0x87, 0x51, 0x59, 0x2e, 0x58, 0x4b, 0xd9, 0x8a, 0xee, 0xea, 0x57, 0x7f, 0x7a, 0xfc,
	0xfa, 0xe8, 0x3f, 0x1e, 0xe1, 0x23, 0x5c, 0xbe, 0xba, 0x74, 0x11, 0x98, 0x07, 0xef, 0xe1, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0x11, 0x9d, 0x4f, 0xcc, 0x05, 0x00, 0x00,
}
