// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto

package cluster // import "github.com/ehazlett/stellar/api/services/cluster/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import v11 "github.com/ehazlett/stellar/api/services/health/v1"
import v1 "github.com/ehazlett/stellar/api/services/node/v1"

// skipping weak import googleapis "github.com/gogo/googleapis"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{0}
}
func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (dst *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(dst, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{1}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ContainersRequest struct {
	Filters              []string `protobuf:"bytes,1,rep,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainersRequest) Reset()         { *m = ContainersRequest{} }
func (m *ContainersRequest) String() string { return proto.CompactTextString(m) }
func (*ContainersRequest) ProtoMessage()    {}
func (*ContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{2}
}
func (m *ContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainersRequest.Unmarshal(m, b)
}
func (m *ContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainersRequest.Marshal(b, m, deterministic)
}
func (dst *ContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainersRequest.Merge(dst, src)
}
func (m *ContainersRequest) XXX_Size() int {
	return xxx_messageInfo_ContainersRequest.Size(m)
}
func (m *ContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainersRequest proto.InternalMessageInfo

func (m *ContainersRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ImagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImagesRequest) Reset()         { *m = ImagesRequest{} }
func (m *ImagesRequest) String() string { return proto.CompactTextString(m) }
func (*ImagesRequest) ProtoMessage()    {}
func (*ImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{3}
}
func (m *ImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagesRequest.Unmarshal(m, b)
}
func (m *ImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagesRequest.Marshal(b, m, deterministic)
}
func (dst *ImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagesRequest.Merge(dst, src)
}
func (m *ImagesRequest) XXX_Size() int {
	return xxx_messageInfo_ImagesRequest.Size(m)
}
func (m *ImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImagesRequest proto.InternalMessageInfo

type NodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesRequest) Reset()         { *m = NodesRequest{} }
func (m *NodesRequest) String() string { return proto.CompactTextString(m) }
func (*NodesRequest) ProtoMessage()    {}
func (*NodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{4}
}
func (m *NodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesRequest.Unmarshal(m, b)
}
func (m *NodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesRequest.Marshal(b, m, deterministic)
}
func (dst *NodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesRequest.Merge(dst, src)
}
func (m *NodesRequest) XXX_Size() int {
	return xxx_messageInfo_NodesRequest.Size(m)
}
func (m *NodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodesRequest proto.InternalMessageInfo

type ContainersResponse struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContainersResponse) Reset()         { *m = ContainersResponse{} }
func (m *ContainersResponse) String() string { return proto.CompactTextString(m) }
func (*ContainersResponse) ProtoMessage()    {}
func (*ContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{5}
}
func (m *ContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainersResponse.Unmarshal(m, b)
}
func (m *ContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainersResponse.Marshal(b, m, deterministic)
}
func (dst *ContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainersResponse.Merge(dst, src)
}
func (m *ContainersResponse) XXX_Size() int {
	return xxx_messageInfo_ContainersResponse.Size(m)
}
func (m *ContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainersResponse proto.InternalMessageInfo

func (m *ContainersResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ImagesResponse struct {
	Images               []*v1.Image `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ImagesResponse) Reset()         { *m = ImagesResponse{} }
func (m *ImagesResponse) String() string { return proto.CompactTextString(m) }
func (*ImagesResponse) ProtoMessage()    {}
func (*ImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{6}
}
func (m *ImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagesResponse.Unmarshal(m, b)
}
func (m *ImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagesResponse.Marshal(b, m, deterministic)
}
func (dst *ImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagesResponse.Merge(dst, src)
}
func (m *ImagesResponse) XXX_Size() int {
	return xxx_messageInfo_ImagesResponse.Size(m)
}
func (m *ImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImagesResponse proto.InternalMessageInfo

func (m *ImagesResponse) GetImages() []*v1.Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Node struct {
	ID                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{7}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type NodesResponse struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesResponse) Reset()         { *m = NodesResponse{} }
func (m *NodesResponse) String() string { return proto.CompactTextString(m) }
func (*NodesResponse) ProtoMessage()    {}
func (*NodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{8}
}
func (m *NodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesResponse.Unmarshal(m, b)
}
func (m *NodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesResponse.Marshal(b, m, deterministic)
}
func (dst *NodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesResponse.Merge(dst, src)
}
func (m *NodesResponse) XXX_Size() int {
	return xxx_messageInfo_NodesResponse.Size(m)
}
func (m *NodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodesResponse proto.InternalMessageInfo

func (m *NodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Container struct {
	Container            *v1.Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Node                 *Node         `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{9}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetContainer() *v1.Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *Container) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{10}
}
func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (dst *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(dst, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type NodeHealth struct {
	Node                 *Node           `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Health               *v11.NodeHealth `protobuf:"bytes,2,opt,name=health" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NodeHealth) Reset()         { *m = NodeHealth{} }
func (m *NodeHealth) String() string { return proto.CompactTextString(m) }
func (*NodeHealth) ProtoMessage()    {}
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{11}
}
func (m *NodeHealth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeHealth.Unmarshal(m, b)
}
func (m *NodeHealth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeHealth.Marshal(b, m, deterministic)
}
func (dst *NodeHealth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeHealth.Merge(dst, src)
}
func (m *NodeHealth) XXX_Size() int {
	return xxx_messageInfo_NodeHealth.Size(m)
}
func (m *NodeHealth) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeHealth.DiscardUnknown(m)
}

var xxx_messageInfo_NodeHealth proto.InternalMessageInfo

func (m *NodeHealth) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeHealth) GetHealth() *v11.NodeHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

type HealthResponse struct {
	Nodes                []*NodeHealth `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_af4c9229db8d807e, []int{12}
}
func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (dst *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(dst, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetNodes() []*NodeHealth {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "stellar.services.cluster.v1.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "stellar.services.cluster.v1.InfoResponse")
	proto.RegisterType((*ContainersRequest)(nil), "stellar.services.cluster.v1.ContainersRequest")
	proto.RegisterType((*ImagesRequest)(nil), "stellar.services.cluster.v1.ImagesRequest")
	proto.RegisterType((*NodesRequest)(nil), "stellar.services.cluster.v1.NodesRequest")
	proto.RegisterType((*ContainersResponse)(nil), "stellar.services.cluster.v1.ContainersResponse")
	proto.RegisterType((*ImagesResponse)(nil), "stellar.services.cluster.v1.ImagesResponse")
	proto.RegisterType((*Node)(nil), "stellar.services.cluster.v1.Node")
	proto.RegisterMapType((map[string]string)(nil), "stellar.services.cluster.v1.Node.LabelsEntry")
	proto.RegisterType((*NodesResponse)(nil), "stellar.services.cluster.v1.NodesResponse")
	proto.RegisterType((*Container)(nil), "stellar.services.cluster.v1.Container")
	proto.RegisterType((*HealthRequest)(nil), "stellar.services.cluster.v1.HealthRequest")
	proto.RegisterType((*NodeHealth)(nil), "stellar.services.cluster.v1.NodeHealth")
	proto.RegisterType((*HealthResponse)(nil), "stellar.services.cluster.v1.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error)
	Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Containers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error) {
	out := new(ImagesResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Images", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error) {
	out := new(NodesResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Nodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.cluster.v1.Cluster/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Containers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	Images(context.Context, *ImagesRequest) (*ImagesResponse, error)
	Nodes(context.Context, *NodesRequest) (*NodesResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Containers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Containers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Containers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Containers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Images_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Images(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Images",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Images(ctx, req.(*ImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Nodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Nodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Nodes(ctx, req.(*NodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.cluster.v1.Cluster/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellar.services.cluster.v1.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Cluster_Info_Handler,
		},
		{
			MethodName: "Containers",
			Handler:    _Cluster_Containers_Handler,
		},
		{
			MethodName: "Images",
			Handler:    _Cluster_Images_Handler,
		},
		{
			MethodName: "Nodes",
			Handler:    _Cluster_Nodes_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Cluster_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto",
}

func init() {
	proto.RegisterFile("github.com/ehazlett/stellar/api/services/cluster/v1/cluster.proto", fileDescriptor_cluster_af4c9229db8d807e)
}

var fileDescriptor_cluster_af4c9229db8d807e = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xec, 0xa6, 0xae, 0x72, 0xd3, 0xe6, 0xa3, 0x43, 0x85, 0x82, 0x41, 0x4a, 0x71, 0xa5,
	0x92, 0x16, 0xd5, 0x56, 0x82, 0x10, 0x3f, 0x55, 0x91, 0xda, 0x52, 0xd4, 0x48, 0x08, 0x24, 0xaf,
	0x10, 0xb0, 0x99, 0xc4, 0x53, 0xc7, 0xc2, 0xf1, 0x04, 0xcf, 0x24, 0x52, 0x58, 0x82, 0x78, 0x02,
	0x24, 0x1e, 0x86, 0xd7, 0x60, 0xcf, 0x02, 0xf1, 0x20, 0x68, 0x7e, 0xec, 0x38, 0x82, 0x26, 0x86,
	0x55, 0xee, 0xcc, 0x9c, 0x7b, 0xee, 0x99, 0x93, 0x7b, 0xc7, 0x70, 0x1c, 0x46, 0x7c, 0x30, 0xee,
	0xb9, 0x7d, 0x3a, 0xf4, 0xc8, 0x00, 0xbf, 0x8f, 0x09, 0xe7, 0x1e, 0xe3, 0x24, 0x8e, 0x71, 0xea,
	0xe1, 0x51, 0xe4, 0x31, 0x92, 0x4e, 0xa2, 0x3e, 0x61, 0x5e, 0x3f, 0x1e, 0x33, 0x4e, 0x52, 0x6f,
	0xd2, 0xce, 0x42, 0x77, 0x94, 0x52, 0x4e, 0xd1, 0x0d, 0x0d, 0x77, 0x33, 0xa8, 0x9b, 0x9d, 0x4f,
	0xda, 0xf6, 0xcd, 0x90, 0xd2, 0x30, 0x26, 0x92, 0x0a, 0x27, 0x09, 0xe5, 0x98, 0x47, 0x34, 0x61,
	0x2a, 0xd5, 0xde, 0x0a, 0x69, 0x48, 0x65, 0xe8, 0x89, 0x48, 0xef, 0x36, 0xe7, 0xea, 0x26, 0x34,
	0x20, 0xa2, 0xa8, 0xf8, 0xd5, 0x80, 0x9d, 0x39, 0xc0, 0x80, 0xe0, 0x98, 0x0f, 0x04, 0x44, 0x45,
	0x0a, 0xe4, 0x6c, 0x40, 0xad, 0x9b, 0x5c, 0x50, 0x9f, 0xbc, 0x1b, 0x13, 0xc6, 0x9d, 0x5d, 0x58,
	0x57, 0x4b, 0x36, 0xa2, 0x09, 0x23, 0xe8, 0x1a, 0x98, 0x51, 0xd0, 0x30, 0xb6, 0x8d, 0x56, 0xf5,
	0xc4, 0xfa, 0xf1, 0xbd, 0x69, 0x76, 0x9f, 0xf8, 0x66, 0x14, 0x38, 0x07, 0xb0, 0x79, 0x4a, 0x13,
	0x8e, 0xa3, 0x84, 0xa4, 0x4c, 0x27, 0xa3, 0x06, 0xac, 0x5d, 0x44, 0x31, 0x27, 0x29, 0x6b, 0x18,
	0xdb, 0x2b, 0xad, 0xaa, 0x9f, 0x2d, 0x9d, 0xff, 0x61, 0xa3, 0x3b, 0xc4, 0x21, 0xc9, 0xa0, 0x4e,
	0x1d, 0xd6, 0x9f, 0xd3, 0x60, 0xb6, 0x7e, 0x03, 0xa8, 0xc8, 0xa7, 0xab, 0x3f, 0x05, 0xe8, 0xe7,
	0xbb, 0x92, 0xb3, 0xd6, 0xd9, 0x75, 0x17, 0x18, 0xe9, 0xe6, 0x24, 0x7e, 0x21, 0xd3, 0xe9, 0x42,
	0x3d, 0x2b, 0xaf, 0x99, 0xef, 0x83, 0x15, 0xc9, 0x1d, 0xcd, 0xda, 0xfc, 0x9d, 0x55, 0x3a, 0x39,
	0x69, 0xbb, 0x32, 0xd3, 0xd7, 0x70, 0xe7, 0xab, 0x01, 0x15, 0xa1, 0xfc, 0x32, 0x67, 0x84, 0x09,
	0x38, 0x08, 0x52, 0xc2, 0x58, 0xc3, 0x14, 0x87, 0x7e, 0xb6, 0x44, 0x67, 0x60, 0xc5, 0xb8, 0x47,
	0x62, 0xd6, 0x58, 0x91, 0x35, 0x0f, 0x16, 0xde, 0x44, 0x14, 0x71, 0x9f, 0x49, 0xfc, 0x59, 0xc2,
	0xd3, 0xa9, 0xaf, 0x93, 0xed, 0x87, 0x50, 0x2b, 0x6c, 0xa3, 0x2b, 0xb0, 0xf2, 0x96, 0x4c, 0x95,
	0x10, 0x5f, 0x84, 0x68, 0x0b, 0x56, 0x27, 0x38, 0x1e, 0x13, 0x5d, 0x5f, 0x2d, 0x1e, 0x99, 0x0f,
	0x0c, 0xe7, 0x1c, 0x36, 0xb4, 0xeb, 0xb9, 0x0d, 0xab, 0xe2, 0x9a, 0x99, 0x0b, 0xb7, 0x96, 0x2a,
	0xf2, 0x15, 0xde, 0xf9, 0x64, 0x40, 0x35, 0xf7, 0x1a, 0x1d, 0x43, 0x35, 0x77, 0x5b, 0x2a, 0xa9,
	0x75, 0x76, 0x2e, 0x37, 0x74, 0xf6, 0x1f, 0xcd, 0xb2, 0xd0, 0x3d, 0xa8, 0x88, 0x73, 0xa9, 0xb9,
	0x94, 0x10, 0x09, 0x17, 0x8d, 0x75, 0x2e, 0xdb, 0x39, 0x6b, 0xa4, 0x8f, 0x06, 0x80, 0x38, 0x57,
	0xbb, 0x39, 0xad, 0xf1, 0x57, 0xb4, 0xe8, 0x31, 0x58, 0x6a, 0x4a, 0xb4, 0x9e, 0x3f, 0x34, 0x9d,
	0x9e, 0x22, 0x9d, 0xa7, 0x45, 0xe8, 0x2c, 0xe7, 0x05, 0xd4, 0x33, 0x59, 0xda, 0xe9, 0xa3, 0x79,
	0xa7, 0x6f, 0x2f, 0x55, 0xa2, 0xf3, 0x55, 0x56, 0xe7, 0x4b, 0x05, 0xd6, 0x4e, 0x15, 0x00, 0xbd,
	0x86, 0x8a, 0x98, 0x51, 0xd4, 0x5a, 0xc8, 0x51, 0x98, 0x6a, 0x7b, 0xaf, 0x04, 0x52, 0xeb, 0x1c,
	0x02, 0xcc, 0x06, 0x11, 0xb9, 0xe5, 0x86, 0x2d, 0x1b, 0x63, 0xdb, 0x2b, 0x8d, 0xd7, 0xe5, 0x30,
	0x58, 0x6a, 0x32, 0xd1, 0xfe, 0x62, 0x8d, 0xc5, 0xd7, 0xc3, 0xbe, 0x53, 0x0a, 0xab, 0x4b, 0x4c,
	0x61, 0x55, 0x36, 0x3d, 0xda, 0x5b, 0xea, 0x79, 0x5e, 0x60, 0xbf, 0x0c, 0x54, 0xf1, 0x3b, 0xd7,
	0x3f, 0x7c, 0xfb, 0xf9, 0xd9, 0xbc, 0x8a, 0x36, 0x0b, 0x6f, 0xbe, 0x7c, 0x86, 0x99, 0xb8, 0x9d,
	0xee, 0xc3, 0xc5, 0x84, 0x73, 0x2d, 0xbc, 0xe4, 0x76, 0xf3, 0x7d, 0x75, 0x72, 0xf4, 0xea, 0xf0,
	0x1f, 0xbe, 0x4d, 0x87, 0x3a, 0x7c, 0xf9, 0x5f, 0xcf, 0x92, 0xdf, 0x81, 0xbb, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xb5, 0xa2, 0xcf, 0xe8, 0xe3, 0x06, 0x00, 0x00,
}
