version = "unstable"

generator = "grpc-gateway"

# Plugins allows one to specify one or more plugins for use in generation.
#
# The common example grpc is provided below.
plugins = []

# Control protoc include paths. Below are usually some good defaults, but feel
# free to try it without them if it works for your project.
[includes]
  # Include paths that will be added before all others. Typically, you want to
  # treat the root of the project as an include, but this may not be necessary.
  #
  # "." is included by default
  before = ["."]

  # Paths that should be treated as include roots in relation to the vendor
  # directory. These will be calculated with the vendor directory nearest the
  # target package.
  #
  # With the example below, we import the gogo protobufs from the vendor
  # directory.
  #
  # This is empty by default.
  vendored = ["github.com/gogo/protobuf", "github.com/gogo/googleapis"]

  # Paths that will be added untouched to the end of the includes. We use
  # `/usr/local/include` to pickup the common install location of protobuf.
  # This is the default.
  # after = ["usr/local/include"]

# This section let's us map protobuf imports to Go packages. These will become
# `-M` directives in the call to the go protobuf generator.
#
# We have a few examples to map packages from the examples.
[packages]
  "gogoproto/gogo.proto"             = "github.com/gogo/protobuf/gogoproto"
  "google/api/annotations.proto"     = "github.com/gogo/googleapis"
  "google/api/http.proto"            = "github.com/gogo/googleapis"
  "google/protobuf/descriptor.proto" = "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
  "google/protobuf/timestamp.proto"  = "github.com/gogo/protobuf/types"
  "google/protobuf/duration.proto"   = "github.com/gogo/protobuf/types"
  "google/protobuf/any.proto"        = "github.com/gogo/protobuf/types"
  "google/protobuf/empty.proto"      = "github.com/gogo/protobuf/types"

