// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/stellar/api/services/node/v1/node.proto

/*
Package node is a generated protocol buffer package.

It is generated from these files:
	github.com/ehazlett/stellar/api/services/node/v1/node.proto

It has these top-level messages:
	ContainersRequest
	Container
	ContainersResponse
	ContainerRequest
	ContainerResponse
	ImagesRequest
	Image
	ImagesResponse
	ContainerNetworkRequest
*/
package node

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"
import google_protobuf2 "github.com/gogo/protobuf/types"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ContainersRequest struct {
}

func (m *ContainersRequest) Reset()                    { *m = ContainersRequest{} }
func (m *ContainersRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainersRequest) ProtoMessage()               {}
func (*ContainersRequest) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{0} }

type Container struct {
	ID          string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image       string                `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Labels      map[string]string     `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Spec        *google_protobuf1.Any `protobuf:"bytes,4,opt,name=spec" json:"spec,omitempty"`
	Snapshotter string                `protobuf:"bytes,5,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Task        *Container_Task       `protobuf:"bytes,6,opt,name=task" json:"task,omitempty"`
	Runtime     string                `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{1} }

func (m *Container) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Container) GetSpec() *google_protobuf1.Any {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Container) GetSnapshotter() string {
	if m != nil {
		return m.Snapshotter
	}
	return ""
}

func (m *Container) GetTask() *Container_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Container) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

type Container_Task struct {
	Pid uint32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (m *Container_Task) Reset()                    { *m = Container_Task{} }
func (m *Container_Task) String() string            { return proto.CompactTextString(m) }
func (*Container_Task) ProtoMessage()               {}
func (*Container_Task) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{1, 1} }

func (m *Container_Task) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type ContainersResponse struct {
	Containers []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
}

func (m *ContainersResponse) Reset()                    { *m = ContainersResponse{} }
func (m *ContainersResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainersResponse) ProtoMessage()               {}
func (*ContainersResponse) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{2} }

func (m *ContainersResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerRequest struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ContainerRequest) Reset()                    { *m = ContainerRequest{} }
func (m *ContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerRequest) ProtoMessage()               {}
func (*ContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{3} }

func (m *ContainerRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ContainerResponse struct {
	Container *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
}

func (m *ContainerResponse) Reset()                    { *m = ContainerResponse{} }
func (m *ContainerResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerResponse) ProtoMessage()               {}
func (*ContainerResponse) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{4} }

func (m *ContainerResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type ImagesRequest struct {
}

func (m *ImagesRequest) Reset()                    { *m = ImagesRequest{} }
func (m *ImagesRequest) String() string            { return proto.CompactTextString(m) }
func (*ImagesRequest) ProtoMessage()               {}
func (*ImagesRequest) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{5} }

type Image struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{6} }

func (m *Image) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ImagesResponse struct {
	Images []*Image `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
}

func (m *ImagesResponse) Reset()                    { *m = ImagesResponse{} }
func (m *ImagesResponse) String() string            { return proto.CompactTextString(m) }
func (*ImagesResponse) ProtoMessage()               {}
func (*ImagesResponse) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{7} }

func (m *ImagesResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type ContainerNetworkRequest struct {
	ID      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IP      string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Network string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Gateway string `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
}

func (m *ContainerNetworkRequest) Reset()                    { *m = ContainerNetworkRequest{} }
func (m *ContainerNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerNetworkRequest) ProtoMessage()               {}
func (*ContainerNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{8} }

func (m *ContainerNetworkRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ContainerNetworkRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ContainerNetworkRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *ContainerNetworkRequest) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainersRequest)(nil), "stellar.services.node.v1.ContainersRequest")
	proto.RegisterType((*Container)(nil), "stellar.services.node.v1.Container")
	proto.RegisterType((*Container_Task)(nil), "stellar.services.node.v1.Container.Task")
	proto.RegisterType((*ContainersResponse)(nil), "stellar.services.node.v1.ContainersResponse")
	proto.RegisterType((*ContainerRequest)(nil), "stellar.services.node.v1.ContainerRequest")
	proto.RegisterType((*ContainerResponse)(nil), "stellar.services.node.v1.ContainerResponse")
	proto.RegisterType((*ImagesRequest)(nil), "stellar.services.node.v1.ImagesRequest")
	proto.RegisterType((*Image)(nil), "stellar.services.node.v1.Image")
	proto.RegisterType((*ImagesResponse)(nil), "stellar.services.node.v1.ImagesResponse")
	proto.RegisterType((*ContainerNetworkRequest)(nil), "stellar.services.node.v1.ContainerNetworkRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	Container(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*ContainerResponse, error)
	Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error)
	SetupContainerNetwork(ctx context.Context, in *ContainerNetworkRequest, opts ...grpc.CallOption) (*google_protobuf2.Empty, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := grpc.Invoke(ctx, "/stellar.services.node.v1.Node/Containers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Container(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*ContainerResponse, error) {
	out := new(ContainerResponse)
	err := grpc.Invoke(ctx, "/stellar.services.node.v1.Node/Container", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error) {
	out := new(ImagesResponse)
	err := grpc.Invoke(ctx, "/stellar.services.node.v1.Node/Images", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SetupContainerNetwork(ctx context.Context, in *ContainerNetworkRequest, opts ...grpc.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc.Invoke(ctx, "/stellar.services.node.v1.Node/SetupContainerNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Containers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	Container(context.Context, *ContainerRequest) (*ContainerResponse, error)
	Images(context.Context, *ImagesRequest) (*ImagesResponse, error)
	SetupContainerNetwork(context.Context, *ContainerNetworkRequest) (*google_protobuf2.Empty, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Containers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Containers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Containers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Containers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Container_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Container(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Container",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Container(ctx, req.(*ContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Images_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Images(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Images",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Images(ctx, req.(*ImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SetupContainerNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SetupContainerNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/SetupContainerNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SetupContainerNetwork(ctx, req.(*ContainerNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellar.services.node.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Containers",
			Handler:    _Node_Containers_Handler,
		},
		{
			MethodName: "Container",
			Handler:    _Node_Container_Handler,
		},
		{
			MethodName: "Images",
			Handler:    _Node_Images_Handler,
		},
		{
			MethodName: "SetupContainerNetwork",
			Handler:    _Node_SetupContainerNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/stellar/api/services/node/v1/node.proto",
}

func init() {
	proto.RegisterFile("github.com/ehazlett/stellar/api/services/node/v1/node.proto", fileDescriptorNode)
}

var fileDescriptorNode = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0x56, 0xd3, 0x2e, 0x53, 0xdf, 0x6a, 0xbf, 0xdf, 0x30, 0x63, 0x98, 0x70, 0x58, 0x15, 0x0e,
	0x44, 0x1b, 0x4a, 0xb4, 0x22, 0x34, 0x60, 0x5c, 0xb6, 0x31, 0xa1, 0x4a, 0x68, 0x42, 0x06, 0x21,
	0x01, 0x27, 0xb7, 0x35, 0x69, 0xd4, 0x34, 0x0e, 0xb1, 0xd3, 0xa9, 0x48, 0x7c, 0x0d, 0x3e, 0x1e,
	0x07, 0xbe, 0x06, 0x17, 0x64, 0xc7, 0x49, 0xc3, 0x50, 0xd5, 0x70, 0x8a, 0xdf, 0xbf, 0x7e, 0xde,
	0xe7, 0x79, 0x63, 0x38, 0x0d, 0x23, 0x39, 0xcd, 0x47, 0xfe, 0x98, 0xcf, 0x03, 0x36, 0xa5, 0x5f,
	0x63, 0x26, 0x65, 0x20, 0x24, 0x8b, 0x63, 0x9a, 0x05, 0x34, 0x8d, 0x02, 0xc1, 0xb2, 0x45, 0x34,
	0x66, 0x22, 0x48, 0xf8, 0x84, 0x05, 0x8b, 0x63, 0xfd, 0xf5, 0xd3, 0x8c, 0x4b, 0x8e, 0xb0, 0x49,
	0xf4, 0xcb, 0x24, 0x5f, 0x07, 0x17, 0xc7, 0xce, 0x5e, 0xc8, 0x43, 0xae, 0x93, 0x02, 0x75, 0x2a,
	0xf2, 0x9d, 0x7b, 0x21, 0xe7, 0x61, 0xcc, 0x02, 0x6d, 0x8d, 0xf2, 0xcf, 0x01, 0x4d, 0x96, 0x26,
	0x74, 0xff, 0x66, 0x88, 0xcd, 0x53, 0x69, 0x82, 0xee, 0x6d, 0xb8, 0x75, 0xc1, 0x13, 0x49, 0xa3,
	0x84, 0x65, 0x82, 0xb0, 0x2f, 0x39, 0x13, 0xd2, 0xfd, 0x65, 0x41, 0xb7, 0xf2, 0xa2, 0x7d, 0xb0,
	0xa2, 0x09, 0x6e, 0xf5, 0x5b, 0x5e, 0xf7, 0xdc, 0xfe, 0xf9, 0xe3, 0xc0, 0x1a, 0xbe, 0x24, 0x56,
	0x34, 0x41, 0x7b, 0xb0, 0x15, 0xcd, 0x69, 0xc8, 0xb0, 0xa5, 0x42, 0xa4, 0x30, 0xd0, 0x2b, 0xb0,
	0x63, 0x3a, 0x62, 0xb1, 0xc0, 0xed, 0x7e, 0xdb, 0xeb, 0x0d, 0x02, 0x7f, 0xdd, 0x24, 0x7e, 0x75,
	0x85, 0xff, 0x5a, 0x57, 0x5c, 0x26, 0x32, 0x5b, 0x12, 0x53, 0x8e, 0x3c, 0xe8, 0x88, 0x94, 0x8d,
	0x71, 0xa7, 0xdf, 0xf2, 0x7a, 0x83, 0x3d, 0xbf, 0x98, 0xc2, 0x2f, 0xa7, 0xf0, 0xcf, 0x92, 0x25,
	0xd1, 0x19, 0xa8, 0x0f, 0x3d, 0x91, 0xd0, 0x54, 0x4c, 0xb9, 0x94, 0x2c, 0xc3, 0x5b, 0x1a, 0x4e,
	0xdd, 0x85, 0x5e, 0x40, 0x47, 0x52, 0x31, 0xc3, 0xb6, 0xee, 0xe5, 0x35, 0x81, 0xf4, 0x8e, 0x8a,
	0x19, 0xd1, 0x55, 0x08, 0xc3, 0x76, 0x96, 0x27, 0x32, 0x9a, 0x33, 0xbc, 0xad, 0x7b, 0x97, 0xa6,
	0xf3, 0x0c, 0x7a, 0x35, 0xe8, 0x68, 0x17, 0xda, 0x33, 0xb6, 0x2c, 0xa8, 0x22, 0xea, 0xa8, 0x38,
	0x5a, 0xd0, 0x38, 0xaf, 0x38, 0xd2, 0xc6, 0x73, 0xeb, 0x69, 0xcb, 0xc1, 0xd0, 0x51, 0x57, 0xa8,
	0x9a, 0xd4, 0xd0, 0xbb, 0x43, 0xd4, 0xd1, 0xfd, 0x00, 0xa8, 0x2e, 0x89, 0x48, 0x79, 0x22, 0x18,
	0xba, 0x00, 0x18, 0x57, 0x5e, 0xdc, 0xd2, 0xdc, 0x3e, 0x68, 0x30, 0x08, 0xa9, 0x95, 0xb9, 0x87,
	0xb0, 0xbb, 0x0a, 0x14, 0x62, 0xaf, 0x93, 0xd7, 0x7d, 0x5f, 0xdb, 0x8c, 0x0a, 0xc5, 0x19, 0x74,
	0xab, 0x76, 0xba, 0xa6, 0x21, 0x88, 0x55, 0x95, 0xfb, 0x3f, 0xec, 0x0c, 0xd5, 0xa6, 0x54, 0xdb,
	0x76, 0x00, 0x5b, 0xda, 0xb1, 0x16, 0xc9, 0x10, 0xfe, 0x2b, 0x2b, 0x0c, 0x8c, 0x13, 0xb0, 0xf5,
	0xb6, 0x95, 0x44, 0x1c, 0xac, 0xc7, 0xa0, 0x2b, 0x89, 0x49, 0x77, 0xbf, 0xc1, 0xdd, 0x0a, 0xd4,
	0x15, 0x93, 0xd7, 0x3c, 0x9b, 0x6d, 0xe0, 0x41, 0xfb, 0xd3, 0x42, 0x3f, 0xe3, 0x7f, 0x43, 0xac,
	0x28, 0x55, 0x5b, 0x91, 0x14, 0x1d, 0x70, 0xbb, 0xd8, 0x0a, 0x63, 0xaa, 0x48, 0x48, 0x25, 0xbb,
	0xa6, 0x4b, 0xbd, 0xbc, 0x5d, 0x52, 0x9a, 0x83, 0xef, 0x6d, 0xe8, 0x5c, 0xf1, 0x09, 0x43, 0x21,
	0xc0, 0x4a, 0x63, 0x74, 0xd4, 0x80, 0xc2, 0x92, 0x2e, 0xe7, 0x51, 0xb3, 0x64, 0xc3, 0xd4, 0xa4,
	0xfe, 0x27, 0x1f, 0x36, 0x91, 0xca, 0x5c, 0x73, 0xd4, 0x28, 0xd7, 0xdc, 0xf2, 0x09, 0xec, 0x42,
	0x21, 0xf4, 0x70, 0x83, 0x12, 0xd5, 0x18, 0xde, 0xe6, 0x44, 0xd3, 0x7c, 0x04, 0x77, 0xde, 0x32,
	0x99, 0xa7, 0x37, 0x85, 0x43, 0xc7, 0x0d, 0x20, 0xfe, 0x29, 0xb2, 0xb3, 0xff, 0xd7, 0x33, 0x72,
	0xa9, 0x1e, 0xc3, 0xf3, 0x93, 0x8f, 0x4f, 0xfe, 0xf5, 0xb5, 0x3e, 0x55, 0xdf, 0x91, 0xad, 0x1b,
	0x3d, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xef, 0x4a, 0x04, 0x58, 0xed, 0x05, 0x00, 0x00,
}
