// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/stellar/api/services/node/v1/node.proto

package node // import "github.com/ehazlett/stellar/api/services/node/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Protocol int32

const (
	Protocol_UNKNOWN Protocol = 0
	Protocol_TCP     Protocol = 1
	Protocol_UDP     Protocol = 2
	Protocol_HTTP    Protocol = 3
)

var Protocol_name = map[int32]string{
	0: "UNKNOWN",
	1: "TCP",
	2: "UDP",
	3: "HTTP",
}
var Protocol_value = map[string]int32{
	"UNKNOWN": 0,
	"TCP":     1,
	"UDP":     2,
	"HTTP":    3,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{0}
}

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{0}
}
func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (dst *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(dst, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{1}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ContainersRequest struct {
	Filters              []string `protobuf:"bytes,1,rep,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainersRequest) Reset()         { *m = ContainersRequest{} }
func (m *ContainersRequest) String() string { return proto.CompactTextString(m) }
func (*ContainersRequest) ProtoMessage()    {}
func (*ContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{2}
}
func (m *ContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainersRequest.Unmarshal(m, b)
}
func (m *ContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainersRequest.Marshal(b, m, deterministic)
}
func (dst *ContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainersRequest.Merge(dst, src)
}
func (m *ContainersRequest) XXX_Size() int {
	return xxx_messageInfo_ContainersRequest.Size(m)
}
func (m *ContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainersRequest proto.InternalMessageInfo

func (m *ContainersRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

type Container struct {
	ID                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string                `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Labels               map[string]string     `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Spec                 *types.Any            `protobuf:"bytes,4,opt,name=spec" json:"spec,omitempty"`
	Snapshotter          string                `protobuf:"bytes,5,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Task                 *Container_Task       `protobuf:"bytes,6,opt,name=task" json:"task,omitempty"`
	Runtime              string                `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Extensions           map[string]*types.Any `protobuf:"bytes,8,rep,name=extensions" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{3}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Container) GetSpec() *types.Any {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Container) GetSnapshotter() string {
	if m != nil {
		return m.Snapshotter
	}
	return ""
}

func (m *Container) GetTask() *Container_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Container) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *Container) GetExtensions() map[string]*types.Any {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type Container_Task struct {
	Pid                  uint32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container_Task) Reset()         { *m = Container_Task{} }
func (m *Container_Task) String() string { return proto.CompactTextString(m) }
func (*Container_Task) ProtoMessage()    {}
func (*Container_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{3, 1}
}
func (m *Container_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container_Task.Unmarshal(m, b)
}
func (m *Container_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container_Task.Marshal(b, m, deterministic)
}
func (dst *Container_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container_Task.Merge(dst, src)
}
func (m *Container_Task) XXX_Size() int {
	return xxx_messageInfo_Container_Task.Size(m)
}
func (m *Container_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Container_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Container_Task proto.InternalMessageInfo

func (m *Container_Task) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type ContainersResponse struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContainersResponse) Reset()         { *m = ContainersResponse{} }
func (m *ContainersResponse) String() string { return proto.CompactTextString(m) }
func (*ContainersResponse) ProtoMessage()    {}
func (*ContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{4}
}
func (m *ContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainersResponse.Unmarshal(m, b)
}
func (m *ContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainersResponse.Marshal(b, m, deterministic)
}
func (dst *ContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainersResponse.Merge(dst, src)
}
func (m *ContainersResponse) XXX_Size() int {
	return xxx_messageInfo_ContainersResponse.Size(m)
}
func (m *ContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainersResponse proto.InternalMessageInfo

func (m *ContainersResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerRequest) Reset()         { *m = ContainerRequest{} }
func (m *ContainerRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerRequest) ProtoMessage()    {}
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{5}
}
func (m *ContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRequest.Unmarshal(m, b)
}
func (m *ContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRequest.Marshal(b, m, deterministic)
}
func (dst *ContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRequest.Merge(dst, src)
}
func (m *ContainerRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerRequest.Size(m)
}
func (m *ContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRequest proto.InternalMessageInfo

func (m *ContainerRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ContainerResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ContainerResponse) Reset()         { *m = ContainerResponse{} }
func (m *ContainerResponse) String() string { return proto.CompactTextString(m) }
func (*ContainerResponse) ProtoMessage()    {}
func (*ContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{6}
}
func (m *ContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerResponse.Unmarshal(m, b)
}
func (m *ContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerResponse.Marshal(b, m, deterministic)
}
func (dst *ContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerResponse.Merge(dst, src)
}
func (m *ContainerResponse) XXX_Size() int {
	return xxx_messageInfo_ContainerResponse.Size(m)
}
func (m *ContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerResponse proto.InternalMessageInfo

func (m *ContainerResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type ImagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImagesRequest) Reset()         { *m = ImagesRequest{} }
func (m *ImagesRequest) String() string { return proto.CompactTextString(m) }
func (*ImagesRequest) ProtoMessage()    {}
func (*ImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{7}
}
func (m *ImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagesRequest.Unmarshal(m, b)
}
func (m *ImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagesRequest.Marshal(b, m, deterministic)
}
func (dst *ImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagesRequest.Merge(dst, src)
}
func (m *ImagesRequest) XXX_Size() int {
	return xxx_messageInfo_ImagesRequest.Size(m)
}
func (m *ImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImagesRequest proto.InternalMessageInfo

type Image struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{8}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ImagesResponse struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImagesResponse) Reset()         { *m = ImagesResponse{} }
func (m *ImagesResponse) String() string { return proto.CompactTextString(m) }
func (*ImagesResponse) ProtoMessage()    {}
func (*ImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{9}
}
func (m *ImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagesResponse.Unmarshal(m, b)
}
func (m *ImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagesResponse.Marshal(b, m, deterministic)
}
func (dst *ImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagesResponse.Merge(dst, src)
}
func (m *ImagesResponse) XXX_Size() int {
	return xxx_messageInfo_ImagesResponse.Size(m)
}
func (m *ImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImagesResponse proto.InternalMessageInfo

func (m *ImagesResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type ContainerNetworkRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Network              string   `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Gateway              string   `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerNetworkRequest) Reset()         { *m = ContainerNetworkRequest{} }
func (m *ContainerNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerNetworkRequest) ProtoMessage()    {}
func (*ContainerNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{10}
}
func (m *ContainerNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerNetworkRequest.Unmarshal(m, b)
}
func (m *ContainerNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerNetworkRequest.Marshal(b, m, deterministic)
}
func (dst *ContainerNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerNetworkRequest.Merge(dst, src)
}
func (m *ContainerNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerNetworkRequest.Size(m)
}
func (m *ContainerNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerNetworkRequest proto.InternalMessageInfo

func (m *ContainerNetworkRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ContainerNetworkRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ContainerNetworkRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *ContainerNetworkRequest) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

type Process struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	Args                 []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Env                  []string `protobuf:"bytes,4,rep,name=env" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{11}
}
func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (dst *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(dst, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Process) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *Process) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Process) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type Mount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Options              []string `protobuf:"bytes,5,rep,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{12}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Mount) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Mount) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Mount) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

// NOTE: this uses a custom json unmarshaller (utils.go); update if fields are changed
type Endpoint struct {
	Service  string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=stellar.services.node.v1.Protocol" json:"protocol,omitempty"`
	Host     string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// config is a generic map that is parsed upon unmarshal that is used to generate the Any
	Config               map[string]string `protobuf:"bytes,5,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EndpointConfig       *types.Any        `protobuf:"bytes,6,opt,name=endpoint_config,json=endpointConfig" json:"endpoint_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{13}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (dst *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(dst, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Endpoint) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_UNKNOWN
}

func (m *Endpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Endpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Endpoint) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Endpoint) GetEndpointConfig() *types.Any {
	if m != nil {
		return m.EndpointConfig
	}
	return nil
}

type PlacementPreference struct {
	NodeIDs              []string          `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds" json:"node_ids,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Replicas             uint64            `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlacementPreference) Reset()         { *m = PlacementPreference{} }
func (m *PlacementPreference) String() string { return proto.CompactTextString(m) }
func (*PlacementPreference) ProtoMessage()    {}
func (*PlacementPreference) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{14}
}
func (m *PlacementPreference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementPreference.Unmarshal(m, b)
}
func (m *PlacementPreference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementPreference.Marshal(b, m, deterministic)
}
func (dst *PlacementPreference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementPreference.Merge(dst, src)
}
func (m *PlacementPreference) XXX_Size() int {
	return xxx_messageInfo_PlacementPreference.Size(m)
}
func (m *PlacementPreference) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementPreference.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementPreference proto.InternalMessageInfo

func (m *PlacementPreference) GetNodeIDs() []string {
	if m != nil {
		return m.NodeIDs
	}
	return nil
}

func (m *PlacementPreference) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PlacementPreference) GetReplicas() uint64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

type Service struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string               `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Runtime              string               `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Snapshotter          string               `protobuf:"bytes,4,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Node                 string               `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Process              *Process             `protobuf:"bytes,6,opt,name=process" json:"process,omitempty"`
	Labels               []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	Network              bool                 `protobuf:"varint,8,opt,name=network,proto3" json:"network,omitempty"`
	Mounts               []*Mount             `protobuf:"bytes,9,rep,name=mounts" json:"mounts,omitempty"`
	Endpoints            []*Endpoint          `protobuf:"bytes,10,rep,name=endpoints" json:"endpoints,omitempty"`
	Replicas             uint64               `protobuf:"varint,11,opt,name=replicas,proto3" json:"replicas,omitempty"`
	PlacementPreference  *PlacementPreference `protobuf:"bytes,12,opt,name=placement_preference,json=placementPreference" json:"placement_preference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{15}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Service) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *Service) GetSnapshotter() string {
	if m != nil {
		return m.Snapshotter
	}
	return ""
}

func (m *Service) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Service) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Service) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Service) GetNetwork() bool {
	if m != nil {
		return m.Network
	}
	return false
}

func (m *Service) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Service) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Service) GetReplicas() uint64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *Service) GetPlacementPreference() *PlacementPreference {
	if m != nil {
		return m.PlacementPreference
	}
	return nil
}

type CreateContainerRequest struct {
	Application          string   `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Service              *Service `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	ContainerID          string   `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{16}
}
func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(dst, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *CreateContainerRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *CreateContainerRequest) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

type DeleteContainerRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContainerRequest) Reset()         { *m = DeleteContainerRequest{} }
func (m *DeleteContainerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContainerRequest) ProtoMessage()    {}
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{17}
}
func (m *DeleteContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContainerRequest.Unmarshal(m, b)
}
func (m *DeleteContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContainerRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContainerRequest.Merge(dst, src)
}
func (m *DeleteContainerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContainerRequest.Size(m)
}
func (m *DeleteContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContainerRequest proto.InternalMessageInfo

func (m *DeleteContainerRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RestartContainerRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartContainerRequest) Reset()         { *m = RestartContainerRequest{} }
func (m *RestartContainerRequest) String() string { return proto.CompactTextString(m) }
func (*RestartContainerRequest) ProtoMessage()    {}
func (*RestartContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0bce8e33d20cf9cb, []int{18}
}
func (m *RestartContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartContainerRequest.Unmarshal(m, b)
}
func (m *RestartContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartContainerRequest.Marshal(b, m, deterministic)
}
func (dst *RestartContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartContainerRequest.Merge(dst, src)
}
func (m *RestartContainerRequest) XXX_Size() int {
	return xxx_messageInfo_RestartContainerRequest.Size(m)
}
func (m *RestartContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartContainerRequest proto.InternalMessageInfo

func (m *RestartContainerRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "stellar.services.node.v1.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "stellar.services.node.v1.InfoResponse")
	proto.RegisterType((*ContainersRequest)(nil), "stellar.services.node.v1.ContainersRequest")
	proto.RegisterType((*Container)(nil), "stellar.services.node.v1.Container")
	proto.RegisterMapType((map[string]*types.Any)(nil), "stellar.services.node.v1.Container.ExtensionsEntry")
	proto.RegisterMapType((map[string]string)(nil), "stellar.services.node.v1.Container.LabelsEntry")
	proto.RegisterType((*Container_Task)(nil), "stellar.services.node.v1.Container.Task")
	proto.RegisterType((*ContainersResponse)(nil), "stellar.services.node.v1.ContainersResponse")
	proto.RegisterType((*ContainerRequest)(nil), "stellar.services.node.v1.ContainerRequest")
	proto.RegisterType((*ContainerResponse)(nil), "stellar.services.node.v1.ContainerResponse")
	proto.RegisterType((*ImagesRequest)(nil), "stellar.services.node.v1.ImagesRequest")
	proto.RegisterType((*Image)(nil), "stellar.services.node.v1.Image")
	proto.RegisterType((*ImagesResponse)(nil), "stellar.services.node.v1.ImagesResponse")
	proto.RegisterType((*ContainerNetworkRequest)(nil), "stellar.services.node.v1.ContainerNetworkRequest")
	proto.RegisterType((*Process)(nil), "stellar.services.node.v1.Process")
	proto.RegisterType((*Mount)(nil), "stellar.services.node.v1.Mount")
	proto.RegisterType((*Endpoint)(nil), "stellar.services.node.v1.Endpoint")
	proto.RegisterMapType((map[string]string)(nil), "stellar.services.node.v1.Endpoint.ConfigEntry")
	proto.RegisterType((*PlacementPreference)(nil), "stellar.services.node.v1.PlacementPreference")
	proto.RegisterMapType((map[string]string)(nil), "stellar.services.node.v1.PlacementPreference.LabelsEntry")
	proto.RegisterType((*Service)(nil), "stellar.services.node.v1.Service")
	proto.RegisterType((*CreateContainerRequest)(nil), "stellar.services.node.v1.CreateContainerRequest")
	proto.RegisterType((*DeleteContainerRequest)(nil), "stellar.services.node.v1.DeleteContainerRequest")
	proto.RegisterType((*RestartContainerRequest)(nil), "stellar.services.node.v1.RestartContainerRequest")
	proto.RegisterEnum("stellar.services.node.v1.Protocol", Protocol_name, Protocol_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	Container(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*ContainerResponse, error)
	Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error)
	SetupContainerNetwork(ctx context.Context, in *ContainerNetworkRequest, opts ...grpc.CallOption) (*types.Empty, error)
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*types.Empty, error)
	DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*types.Empty, error)
	RestartContainer(ctx context.Context, in *RestartContainerRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Containers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/Containers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Container(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*ContainerResponse, error) {
	out := new(ContainerResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/Container", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Images(ctx context.Context, in *ImagesRequest, opts ...grpc.CallOption) (*ImagesResponse, error) {
	out := new(ImagesResponse)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/Images", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SetupContainerNetwork(ctx context.Context, in *ContainerNetworkRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/SetupContainerNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/CreateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/DeleteContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) RestartContainer(ctx context.Context, in *RestartContainerRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/stellar.services.node.v1.Node/RestartContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Containers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	Container(context.Context, *ContainerRequest) (*ContainerResponse, error)
	Images(context.Context, *ImagesRequest) (*ImagesResponse, error)
	SetupContainerNetwork(context.Context, *ContainerNetworkRequest) (*types.Empty, error)
	CreateContainer(context.Context, *CreateContainerRequest) (*types.Empty, error)
	DeleteContainer(context.Context, *DeleteContainerRequest) (*types.Empty, error)
	RestartContainer(context.Context, *RestartContainerRequest) (*types.Empty, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Containers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Containers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Containers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Containers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Container_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Container(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Container",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Container(ctx, req.(*ContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Images_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Images(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/Images",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Images(ctx, req.(*ImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SetupContainerNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SetupContainerNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/SetupContainerNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SetupContainerNetwork(ctx, req.(*ContainerNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/DeleteContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DeleteContainer(ctx, req.(*DeleteContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_RestartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).RestartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.node.v1.Node/RestartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).RestartContainer(ctx, req.(*RestartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellar.services.node.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Node_Info_Handler,
		},
		{
			MethodName: "Containers",
			Handler:    _Node_Containers_Handler,
		},
		{
			MethodName: "Container",
			Handler:    _Node_Container_Handler,
		},
		{
			MethodName: "Images",
			Handler:    _Node_Images_Handler,
		},
		{
			MethodName: "SetupContainerNetwork",
			Handler:    _Node_SetupContainerNetwork_Handler,
		},
		{
			MethodName: "CreateContainer",
			Handler:    _Node_CreateContainer_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _Node_DeleteContainer_Handler,
		},
		{
			MethodName: "RestartContainer",
			Handler:    _Node_RestartContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/stellar/api/services/node/v1/node.proto",
}

func init() {
	proto.RegisterFile("github.com/ehazlett/stellar/api/services/node/v1/node.proto", fileDescriptor_node_0bce8e33d20cf9cb)
}

var fileDescriptor_node_0bce8e33d20cf9cb = []byte{
	// 1268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xcd, 0x72, 0xe3, 0xc4,
	0x13, 0xff, 0xdb, 0x56, 0xfc, 0xd1, 0xca, 0x87, 0xff, 0xb3, 0x21, 0x2b, 0xcc, 0x21, 0x46, 0x14,
	0xc1, 0x95, 0x65, 0xed, 0x8d, 0x53, 0x54, 0x58, 0x02, 0x14, 0x9b, 0x0f, 0xc0, 0x05, 0x04, 0x33,
	0x49, 0xa0, 0x60, 0x8b, 0x0a, 0x8a, 0x35, 0x56, 0x54, 0x91, 0x35, 0x42, 0x33, 0xce, 0x62, 0xaa,
	0xb8, 0xf2, 0x26, 0x9c, 0x78, 0x17, 0x1e, 0x21, 0x87, 0x5c, 0x38, 0xf0, 0x12, 0xd4, 0x8c, 0x46,
	0xb2, 0xe2, 0x44, 0xb6, 0x53, 0x9c, 0xdc, 0xdd, 0xd3, 0x5f, 0xea, 0xf9, 0x75, 0xf7, 0x18, 0x76,
	0x1d, 0x97, 0x5f, 0x0c, 0xcf, 0x9b, 0x3d, 0x3a, 0x68, 0x91, 0x0b, 0xeb, 0x57, 0x8f, 0x70, 0xde,
	0x62, 0x9c, 0x78, 0x9e, 0x15, 0xb6, 0xac, 0xc0, 0x6d, 0x31, 0x12, 0x5e, 0xb9, 0x3d, 0xc2, 0x5a,
	0x3e, 0xb5, 0x49, 0xeb, 0x6a, 0x4b, 0xfe, 0x36, 0x83, 0x90, 0x72, 0x8a, 0x0c, 0xa5, 0xd8, 0x8c,
	0x95, 0x9a, 0xf2, 0xf0, 0x6a, 0xab, 0xb6, 0xea, 0x50, 0x87, 0x4a, 0xa5, 0x96, 0xa0, 0x22, 0xfd,
	0xda, 0xeb, 0x0e, 0xa5, 0x8e, 0x47, 0x5a, 0x92, 0x3b, 0x1f, 0xf6, 0x5b, 0x96, 0x3f, 0x52, 0x47,
	0x6f, 0x4c, 0x1e, 0x91, 0x41, 0xc0, 0xd5, 0xa1, 0xb9, 0x04, 0x7a, 0xc7, 0xef, 0x53, 0x4c, 0x7e,
	0x1e, 0x12, 0xc6, 0xcd, 0x0d, 0x58, 0x8c, 0x58, 0x16, 0x50, 0x9f, 0x11, 0xb4, 0x06, 0x79, 0xd7,
	0x36, 0x72, 0xf5, 0x5c, 0xa3, 0xb2, 0x57, 0xbc, 0xb9, 0x5e, 0xcf, 0x77, 0x0e, 0x70, 0xde, 0xb5,
	0xcd, 0xa7, 0xf0, 0xff, 0x7d, 0xea, 0x73, 0xcb, 0xf5, 0x49, 0xc8, 0x94, 0x31, 0x32, 0xa0, 0xd4,
	0x77, 0x3d, 0x4e, 0x42, 0x66, 0xe4, 0xea, 0x85, 0x46, 0x05, 0xc7, 0xac, 0xf9, 0x87, 0x06, 0x95,
	0x44, 0x3f, 0xcb, 0x29, 0x5a, 0x85, 0x05, 0x77, 0x60, 0x39, 0xc4, 0xc8, 0x8b, 0x23, 0x1c, 0x31,
	0xe8, 0x33, 0x28, 0x7a, 0xd6, 0x39, 0xf1, 0x98, 0x51, 0xa8, 0x17, 0x1a, 0x7a, 0xbb, 0xd5, 0xcc,
	0x2a, 0x4d, 0x33, 0x09, 0xd1, 0xfc, 0x52, 0x5a, 0x1c, 0xfa, 0x3c, 0x1c, 0x61, 0x65, 0x8e, 0x1a,
	0xa0, 0xb1, 0x80, 0xf4, 0x0c, 0xad, 0x9e, 0x6b, 0xe8, 0xed, 0xd5, 0x66, 0x54, 0x96, 0x66, 0x5c,
	0x96, 0xe6, 0x0b, 0x7f, 0x84, 0xa5, 0x06, 0xaa, 0x83, 0xce, 0x7c, 0x2b, 0x60, 0x17, 0x94, 0x73,
	0x12, 0x1a, 0x0b, 0x32, 0x9d, 0xb4, 0x08, 0x7d, 0x08, 0x1a, 0xb7, 0xd8, 0xa5, 0x51, 0x94, 0xbe,
	0x1a, 0xf3, 0xa4, 0x74, 0x62, 0xb1, 0x4b, 0x2c, 0xad, 0x44, 0xa1, 0xc2, 0xa1, 0xcf, 0xdd, 0x01,
	0x31, 0x4a, 0xd2, 0x77, 0xcc, 0xa2, 0x63, 0x00, 0xf2, 0x0b, 0x27, 0x3e, 0x73, 0xa9, 0xcf, 0x8c,
	0xb2, 0xfc, 0xe0, 0xed, 0x79, 0xbc, 0x1f, 0x26, 0x56, 0xd1, 0x47, 0xa7, 0xdc, 0xd4, 0x9e, 0x83,
	0x9e, 0xaa, 0x07, 0xaa, 0x42, 0xe1, 0x92, 0x8c, 0xa2, 0xfa, 0x63, 0x41, 0x8a, 0xc2, 0x5f, 0x59,
	0xde, 0x30, 0x29, 0xbc, 0x64, 0x3e, 0xc8, 0xbf, 0x9f, 0xab, 0x19, 0xa0, 0x89, 0xbc, 0x85, 0x4d,
	0xa0, 0xee, 0x6c, 0x09, 0x0b, 0xb2, 0x76, 0x0c, 0x2b, 0x13, 0x31, 0xef, 0x71, 0xbc, 0x99, 0x76,
	0x9c, 0x55, 0xf3, 0x71, 0x38, 0xf3, 0x7b, 0x40, 0x69, 0x58, 0x29, 0x10, 0xee, 0x03, 0xf4, 0x12,
	0xa9, 0x84, 0x96, 0xde, 0x7e, 0x6b, 0x8e, 0xa2, 0xe0, 0x94, 0x99, 0xb9, 0x09, 0xd5, 0xf1, 0x81,
	0x02, 0x6c, 0x16, 0xba, 0xbf, 0x4d, 0xa1, 0x3b, 0xc9, 0xe2, 0x05, 0x54, 0x12, 0x77, 0xd2, 0x66,
	0xce, 0x24, 0xc6, 0x56, 0xe6, 0x0a, 0x2c, 0x75, 0x04, 0xa6, 0xe3, 0x8e, 0x31, 0xd7, 0x61, 0x41,
	0x0a, 0x32, 0x33, 0xe9, 0xc0, 0x72, 0x6c, 0xa1, 0xd2, 0xd8, 0x81, 0xa2, 0xec, 0x8b, 0xb8, 0x10,
	0xeb, 0xd9, 0x39, 0x48, 0x4b, 0xac, 0xd4, 0xcd, 0xdf, 0xe0, 0x71, 0x92, 0xd4, 0x11, 0xe1, 0xaf,
	0x68, 0x78, 0x39, 0xa3, 0x0e, 0x52, 0x1e, 0x44, 0xa0, 0x50, 0xf2, 0x2e, 0xce, 0xbb, 0x81, 0xc0,
	0xaf, 0x1f, 0x79, 0x30, 0x0a, 0x11, 0x7e, 0x15, 0x2b, 0x4e, 0x1c, 0x8b, 0x93, 0x57, 0xd6, 0x48,
	0xb6, 0x59, 0x05, 0xc7, 0xac, 0x79, 0x0c, 0xa5, 0x6e, 0x48, 0x7b, 0x84, 0x31, 0x81, 0x93, 0xe1,
	0x18, 0x4c, 0x43, 0xd7, 0x16, 0x12, 0xc7, 0xb5, 0x65, 0xa4, 0x25, 0x2c, 0x48, 0x84, 0x40, 0xb3,
	0x42, 0x27, 0xea, 0xf9, 0x0a, 0x96, 0xb4, 0xd0, 0x22, 0xfe, 0x95, 0xa1, 0x49, 0x91, 0x20, 0x4d,
	0x0a, 0x0b, 0x5f, 0xd1, 0xa1, 0xcf, 0x85, 0x3a, 0x1f, 0x05, 0x44, 0x61, 0x4f, 0xd2, 0x68, 0x0d,
	0x8a, 0x8c, 0x0e, 0xc3, 0x5e, 0x0c, 0x6b, 0xc5, 0x89, 0xee, 0xb6, 0x09, 0xe3, 0xae, 0x6f, 0x71,
	0x97, 0xfa, 0x2a, 0xcf, 0xb4, 0x48, 0x7c, 0x05, 0x0d, 0xb8, 0x6c, 0xc1, 0x85, 0x68, 0x90, 0x29,
	0xd6, 0xfc, 0x2b, 0x0f, 0xe5, 0x43, 0xdf, 0x0e, 0xa8, 0xeb, 0xcb, 0x79, 0xa7, 0x6a, 0xae, 0xe2,
	0xc6, 0x2c, 0xfa, 0x18, 0xca, 0x12, 0xe2, 0x3d, 0xea, 0xc9, 0xe0, 0xcb, 0x6d, 0x33, 0xfb, 0x9a,
	0xba, 0x4a, 0x13, 0x27, 0x36, 0xe2, 0x73, 0x2e, 0x28, 0xe3, 0xaa, 0xba, 0x92, 0x16, 0xb2, 0x80,
	0x86, 0x5c, 0xe6, 0xbb, 0x84, 0x25, 0x8d, 0x3e, 0x85, 0x62, 0x8f, 0xfa, 0x7d, 0xd7, 0x91, 0x79,
	0xea, 0xed, 0x66, 0x76, 0x94, 0x38, 0x6b, 0x81, 0xcc, 0xbe, 0xeb, 0xa8, 0xd1, 0x18, 0x59, 0xa3,
	0x8f, 0x60, 0x85, 0xa8, 0xf3, 0x33, 0xe5, 0xb0, 0x38, 0xa5, 0x63, 0x97, 0x63, 0xe5, 0xc8, 0x97,
	0x18, 0x30, 0x29, 0xaf, 0x0f, 0x19, 0x30, 0xe6, 0xdf, 0x39, 0x78, 0xd4, 0xf5, 0xac, 0x1e, 0x19,
	0x10, 0x9f, 0x77, 0x43, 0xd2, 0x27, 0x21, 0xf1, 0x7b, 0x04, 0x6d, 0x40, 0x59, 0x64, 0x7e, 0xe6,
	0xda, 0x6a, 0x99, 0xec, 0xe9, 0x37, 0xd7, 0xeb, 0xa5, 0x23, 0x6a, 0x93, 0xce, 0x01, 0xc3, 0x25,
	0x71, 0xd8, 0xb1, 0x19, 0xfa, 0x26, 0xd9, 0x0e, 0x79, 0x59, 0x81, 0xe7, 0x53, 0xea, 0x7c, 0x37,
	0xcc, 0xbd, 0x7b, 0xa2, 0x06, 0xe5, 0x90, 0x04, 0x9e, 0xdb, 0xb3, 0x98, 0xbc, 0x00, 0x0d, 0x27,
	0xfc, 0x7f, 0x18, 0xa5, 0xe6, 0x3f, 0x05, 0x28, 0x1d, 0x2b, 0x7c, 0x20, 0xd0, 0x7c, 0x6b, 0x90,
	0xc0, 0x55, 0xd0, 0x19, 0xdb, 0x2f, 0xb5, 0x2a, 0x0a, 0xb7, 0x57, 0xc5, 0xc4, 0x92, 0xd2, 0xee,
	0x2e, 0x29, 0x11, 0x85, 0xda, 0x44, 0xed, 0x2f, 0x49, 0xa3, 0x5d, 0x28, 0x05, 0x51, 0x1b, 0xaa,
	0x1b, 0x7e, 0x73, 0x2a, 0x30, 0x85, 0x22, 0x8e, 0x2d, 0x44, 0x47, 0xa9, 0x62, 0x97, 0x64, 0x5b,
	0xc4, 0x15, 0x4b, 0xcd, 0x83, 0x72, 0x3d, 0xd7, 0x28, 0x8f, 0xe7, 0xc1, 0x0e, 0x14, 0x07, 0xa2,
	0x41, 0x99, 0x51, 0x99, 0x35, 0xad, 0x64, 0x23, 0x63, 0xa5, 0x8e, 0x3e, 0x81, 0x4a, 0x0c, 0x32,
	0x66, 0x80, 0xb4, 0x35, 0x67, 0x83, 0x1b, 0x8f, 0x8d, 0x6e, 0x5d, 0xa3, 0x7e, 0xfb, 0x1a, 0xd1,
	0x4f, 0xb0, 0x1a, 0xc4, 0x68, 0x38, 0x0b, 0x12, 0x38, 0x18, 0x8b, 0xb2, 0x24, 0x4f, 0x1f, 0x84,
	0x21, 0xfc, 0x28, 0xb8, 0x2b, 0x34, 0xff, 0xcc, 0xc1, 0xda, 0x7e, 0x48, 0x2c, 0x4e, 0xee, 0x6c,
	0x9d, 0x3a, 0xe8, 0x56, 0x20, 0x13, 0x91, 0xf3, 0x27, 0xc2, 0x40, 0x5a, 0x24, 0x2e, 0x29, 0x1e,
	0x2c, 0xf9, 0x59, 0x97, 0xa4, 0x20, 0x35, 0x9e, 0x3d, 0x6d, 0x58, 0x4c, 0x36, 0xce, 0x99, 0x6b,
	0x47, 0xb0, 0xd9, 0x5b, 0xb9, 0xb9, 0x5e, 0xd7, 0x93, 0x54, 0x3a, 0x07, 0x58, 0x4f, 0x94, 0x3a,
	0xb6, 0xf9, 0x0c, 0xd6, 0x0e, 0x88, 0x47, 0xee, 0x49, 0x36, 0x6b, 0x31, 0x6d, 0xc1, 0x63, 0x4c,
	0x18, 0xb7, 0x42, 0x3e, 0xaf, 0xc9, 0xe6, 0x36, 0x94, 0xe3, 0x51, 0x87, 0x74, 0x28, 0x9d, 0x1e,
	0x7d, 0x71, 0xf4, 0xf5, 0x77, 0x47, 0xd5, 0xff, 0xa1, 0x12, 0x14, 0x4e, 0xf6, 0xbb, 0xd5, 0x9c,
	0x20, 0x4e, 0x0f, 0xba, 0xd5, 0x3c, 0x2a, 0x83, 0xf6, 0xf9, 0xc9, 0x49, 0xb7, 0x5a, 0x68, 0xff,
	0x5e, 0x04, 0x4d, 0x34, 0x3d, 0x3a, 0x05, 0x4d, 0xbc, 0x4c, 0xd1, 0xdb, 0x53, 0xf6, 0xdd, 0xf8,
	0x21, 0x5b, 0xdb, 0x98, 0xa5, 0xa6, 0xd6, 0xa9, 0x03, 0x30, 0x7e, 0x71, 0xa0, 0x27, 0x73, 0x2c,
	0xf4, 0x78, 0x79, 0xd7, 0xde, 0x9d, 0x4f, 0x59, 0x05, 0xb2, 0xd3, 0x2f, 0xe0, 0xcd, 0x79, 0x1e,
	0x0e, 0x2a, 0xcc, 0x93, 0xb9, 0x74, 0x55, 0x94, 0x97, 0x50, 0x8c, 0xde, 0x0b, 0xe8, 0x9d, 0x19,
	0xef, 0x82, 0xe4, 0x33, 0x1a, 0xb3, 0x15, 0x95, 0xf3, 0x73, 0x78, 0xed, 0x98, 0xf0, 0x61, 0x30,
	0xf9, 0x8c, 0x40, 0x5b, 0x73, 0xa4, 0x78, 0xfb, 0xc9, 0x51, 0x5b, 0xbb, 0xb3, 0x58, 0x0e, 0xc5,
	0xbf, 0x12, 0xf4, 0x12, 0x56, 0x26, 0xda, 0x06, 0x3d, 0x9b, 0xe2, 0xfd, 0xde, 0x0e, 0x9b, 0xe6,
	0x7c, 0x02, 0xe6, 0xd3, 0x9c, 0xdf, 0xdf, 0x11, 0x99, 0xce, 0x7f, 0x84, 0xea, 0x64, 0x47, 0x4c,
	0x2b, 0x4c, 0x46, 0xf7, 0x64, 0xb9, 0xdf, 0xdb, 0xf9, 0xe1, 0xbd, 0x87, 0xfe, 0x9f, 0xdc, 0x15,
	0xbf, 0xe7, 0x45, 0xe9, 0x68, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0x33, 0x1f, 0x38,
	0x8f, 0x0e, 0x00, 0x00,
}
