// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/stellar/api/services/health/v1/health.proto

/*
Package health is a generated protocol buffer package.

It is generated from these files:
	github.com/ehazlett/stellar/api/services/health/v1/health.proto

It has these top-level messages:
	InfoRequest
	InfoResponse
	NodeHealth
	HealthResponse
	Peer
*/
package health

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import google_protobuf1 "github.com/gogo/protobuf/types"
import google_protobuf2 "github.com/gogo/protobuf/types"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptorHealth, []int{0} }

type InfoResponse struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptorHealth, []int{1} }

func (m *InfoResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type NodeHealth struct {
	OSName    string `protobuf:"bytes,1,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OSVersion string `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	// TODO: use gogoproto.stdtime (returning panic: message/group field time.Time:bytes without pointer when trying to use)
	StartedAt   *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	Cpus        int64                       `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryTotal int64                       `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryFree  int64                       `protobuf:"varint,6,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	MemoryUsed  int64                       `protobuf:"varint,7,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	Peers       []*Peer                     `protobuf:"bytes,8,rep,name=peers" json:"peers,omitempty"`
}

func (m *NodeHealth) Reset()                    { *m = NodeHealth{} }
func (m *NodeHealth) String() string            { return proto.CompactTextString(m) }
func (*NodeHealth) ProtoMessage()               {}
func (*NodeHealth) Descriptor() ([]byte, []int) { return fileDescriptorHealth, []int{2} }

func (m *NodeHealth) GetOSName() string {
	if m != nil {
		return m.OSName
	}
	return ""
}

func (m *NodeHealth) GetOSVersion() string {
	if m != nil {
		return m.OSVersion
	}
	return ""
}

func (m *NodeHealth) GetStartedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *NodeHealth) GetCpus() int64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *NodeHealth) GetMemoryTotal() int64 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

func (m *NodeHealth) GetMemoryFree() int64 {
	if m != nil {
		return m.MemoryFree
	}
	return 0
}

func (m *NodeHealth) GetMemoryUsed() int64 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *NodeHealth) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type HealthResponse struct {
	Health *NodeHealth `protobuf:"bytes,1,opt,name=health" json:"health,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptorHealth, []int{3} }

func (m *HealthResponse) GetHealth() *NodeHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

type Peer struct {
	ID      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptorHealth, []int{4} }

func (m *Peer) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "stellar.services.health.v1.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "stellar.services.health.v1.InfoResponse")
	proto.RegisterType((*NodeHealth)(nil), "stellar.services.health.v1.NodeHealth")
	proto.RegisterType((*HealthResponse)(nil), "stellar.services.health.v1.HealthResponse")
	proto.RegisterType((*Peer)(nil), "stellar.services.health.v1.Peer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Health service

type HealthClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Health(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/stellar.services.health.v1.Health/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) Health(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/stellar.services.health.v1.Health/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Health service

type HealthServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Health(context.Context, *google_protobuf1.Empty) (*HealthResponse, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.health.v1.Health/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellar.services.health.v1.Health/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Health(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellar.services.health.v1.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Health_Info_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Health_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/stellar/api/services/health/v1/health.proto",
}

func init() {
	proto.RegisterFile("github.com/ehazlett/stellar/api/services/health/v1/health.proto", fileDescriptorHealth)
}

var fileDescriptorHealth = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x49, 0x76, 0x9b, 0x75, 0x4f, 0x5a, 0x2f, 0x06, 0x29, 0x21, 0x5e, 0x24, 0x46, 0xa8,
	0x41, 0x24, 0xa1, 0x2b, 0x88, 0xa5, 0xa0, 0x58, 0x54, 0x2c, 0x48, 0x5b, 0xd2, 0x2a, 0xe8, 0x4d,
	0x98, 0xdd, 0x9c, 0xcd, 0x06, 0x92, 0x9d, 0x38, 0x33, 0x59, 0xa8, 0x6f, 0xe5, 0x73, 0xf8, 0x0e,
	0x7b, 0xb1, 0x4f, 0x22, 0xc9, 0xcc, 0xd6, 0x55, 0xe9, 0x4a, 0xaf, 0x72, 0x3e, 0x7e, 0x33, 0x27,
	0xe7, 0xfc, 0xcf, 0xc0, 0xeb, 0xbc, 0x90, 0xb3, 0x66, 0x1c, 0x4d, 0x58, 0x15, 0xe3, 0x8c, 0x7e,
	0x2f, 0x51, 0xca, 0x58, 0x48, 0x2c, 0x4b, 0xca, 0x63, 0x5a, 0x17, 0xb1, 0x40, 0xbe, 0x28, 0x26,
	0x28, 0xe2, 0x19, 0xd2, 0x52, 0xce, 0xe2, 0xc5, 0xa1, 0xb6, 0xa2, 0x9a, 0x33, 0xc9, 0x88, 0xab,
	0xe1, 0x68, 0x0d, 0x46, 0x3a, 0xbd, 0x38, 0x74, 0x1f, 0xe4, 0x2c, 0x67, 0x1d, 0x16, 0xb7, 0x96,
	0x3a, 0xe1, 0x3e, 0xcc, 0x19, 0xcb, 0x4b, 0x8c, 0x3b, 0x6f, 0xdc, 0x4c, 0x63, 0xac, 0x6a, 0x79,
	0xad, 0x93, 0xde, 0xdf, 0x49, 0x59, 0x54, 0x28, 0x24, 0xad, 0x6a, 0x05, 0x04, 0x7b, 0x60, 0x9f,
	0xce, 0xa7, 0x2c, 0xc1, 0x6f, 0x0d, 0x0a, 0x19, 0x1c, 0xc0, 0xae, 0x72, 0x45, 0xcd, 0xe6, 0x02,
	0xc9, 0x3e, 0x98, 0x45, 0xe6, 0x18, 0xbe, 0x11, 0x0e, 0x4f, 0xac, 0xd5, 0xd2, 0x33, 0x4f, 0xdf,
	0x26, 0x66, 0x91, 0x05, 0x3f, 0x4d, 0x80, 0x33, 0x96, 0xe1, 0x87, 0xee, 0xe7, 0xc8, 0x63, 0x18,
	0x30, 0x91, 0xce, 0x69, 0x85, 0x9a, 0x85, 0xd5, 0xd2, 0xb3, 0xce, 0x2f, 0xcf, 0x68, 0x85, 0x89,
	0xc5, 0x44, 0xfb, 0x25, 0xcf, 0x00, 0x98, 0x48, 0x17, 0xc8, 0x45, 0xc1, 0xe6, 0x8e, 0xd9, 0x71,
	0x7b, 0xab, 0xa5, 0x37, 0x3c, 0xbf, 0xfc, 0xac, 0x82, 0xc9, 0x90, 0x09, 0x6d, 0x92, 0x23, 0x00,
	0x21, 0x29, 0x97, 0x98, 0xa5, 0x54, 0x3a, 0x3d, 0xdf, 0x08, 0xed, 0x91, 0x1b, 0xa9, 0x76, 0xa2,
	0x75, 0x3b, 0xd1, 0xd5, 0xba, 0x9d, 0x64, 0xa8, 0xe9, 0x37, 0x92, 0x10, 0xe8, 0x4f, 0xea, 0x46,
	0x38, 0x7d, 0xdf, 0x08, 0x7b, 0x49, 0x67, 0x93, 0x47, 0xb0, 0x5b, 0x61, 0xc5, 0xf8, 0x75, 0x2a,
	0x99, 0xa4, 0xa5, 0xb3, 0xd3, 0xe5, 0x6c, 0x15, 0xbb, 0x6a, 0x43, 0xc4, 0x03, 0xed, 0xa6, 0x53,
	0x8e, 0xe8, 0x58, 0x1d, 0x01, 0x2a, 0xf4, 0x9e, 0x23, 0x6e, 0x00, 0x8d, 0xc0, 0xcc, 0x19, 0x6c,
	0x02, 0x9f, 0x04, 0x66, 0xe4, 0x05, 0xec, 0xd4, 0x88, 0x5c, 0x38, 0xf7, 0xfc, 0x5e, 0x68, 0x8f,
	0xfc, 0xe8, 0x76, 0x31, 0xa3, 0x0b, 0x44, 0x9e, 0x28, 0x3c, 0xb8, 0x80, 0xfb, 0x6a, 0x90, 0x37,
	0x73, 0x7f, 0x05, 0x96, 0x42, 0xbb, 0x79, 0xda, 0xa3, 0x83, 0x6d, 0x57, 0xfd, 0x16, 0x22, 0xd1,
	0xa7, 0x82, 0x97, 0xd0, 0x6f, 0x0b, 0xdc, 0xa6, 0x1f, 0x71, 0x60, 0x40, 0xb3, 0x8c, 0xa3, 0x10,
	0x4a, 0x88, 0x64, 0xed, 0x8e, 0x7e, 0x18, 0x60, 0x69, 0x55, 0xbf, 0x40, 0xbf, 0x5d, 0x06, 0xf2,
	0x64, 0x5b, 0xf1, 0x8d, 0xed, 0x71, 0xc3, 0xff, 0x83, 0xba, 0xbf, 0x8f, 0x37, 0x45, 0xf6, 0xff,
	0xd1, 0xf4, 0x5d, 0xbb, 0xbf, 0xee, 0xd3, 0x6d, 0x77, 0xfd, 0x39, 0xad, 0x93, 0xe3, 0xaf, 0x47,
	0x77, 0x7f, 0x77, 0xc7, 0xca, 0x1a, 0x5b, 0x5d, 0xe1, 0xe7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0xee, 0x11, 0x8d, 0xbb, 0x03, 0x00, 0x00,
}
